services:
  - type: web
    name: bookpro-backend
    runtime: python
    buildCommand: pip install pipenv && pipenv install --deploy
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: https://bookpro-sc0z.onrender.com
        fromDatabase:
          name: bookpro-db
          property: connectionString
      - key: vGuXgidGMnqXUUKdoOgx3dbydayC6Hs6JLK2oNWSc5c=
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://book-pro-wp54.vercel.app/,http://localhost:5173,http://localhost:3000
