from datetime import date, datetime, time
from app import app
from auth import generate_token, hash_password
from model import (
    Appointment, Doctor, Hospital, MedicalRecord, Patient, Prescription,
    Review, User, db, DoctorSchedule, Notification, DoctorDocument,
)
from sqlalchemy import text

with app.app_context():
    db.session.query(Notification).delete()
    db.session.query(DoctorDocument).delete()
    db.session.query(DoctorSchedule).delete()
    db.session.query(Prescription).delete()
    db.session.query(Review).delete()
    db.session.query(MedicalRecord).delete()
    db.session.query(Appointment).delete()
    db.session.query(Doctor).delete()
    db.session.query(Patient).delete()
    db.session.query(Hospital).delete()
    db.session.query(User).delete()
    db.session.commit()

    db.session.execute(text("ALTER SEQUENCE users_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE patients_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE doctors_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE hospitals_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE appointments_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE reviews_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE medical_records_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE prescriptions_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE doctor_schedules_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE notifications_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE doctor_documents_id_seq RESTART WITH 1"))
    db.session.commit()

    admin_user = User(
        first_name="Admin",
        last_name="User",
        email="admin@example.com",
        phone="0700000001",
        password=hash_password("admin123"),
        role="admin",
        token=generate_token(),
        email_verified=True,
        email_verification_token=None,
    )
    db.session.add(admin_user)
    db.session.commit()
    print(f"Created admin user with id: {admin_user.id}, token: {admin_user.token}")

    hospitals = [
        Hospital(
            name="Nairobi General Hospital",
            address="001 Hospital Hill, Nairobi",
            phone="0201234567",
            email="info@nairobigenhospital.co.ke",
            website="https://nairobigenhospital.co.ke",
        ),
        Hospital(
            name="Mombasa Medical Centre",
            address="78 Nyali Bridge Road, Mombasa",
            phone="0412345678",
            email="info@mombasamedical.co.ke",
            website="https://mombasamedical.co.ke",
        ),
        Hospital(
            name="Kisumu County Referral",
            address="12 Lake Basin Road, Kisumu",
            phone="0571234567",
            email="info@kisumuhospital.co.ke",
            website="https://kisumuhospital.co.ke",
        ),
    ]
    db.session.add_all(hospitals)
    db.session.commit()
    print(f"Seeded {len(hospitals)} hospitals.")

    doctors = [
        Doctor(
            user_id=admin_user.id,
            first_name="Admin",
            last_name="User",
            email="admin@example.com",
            specialty="General Practice",
            specialties="Family Medicine,Preventive Care,Health Screenings",
            profile_image="https://placehold.co/150x150/0F7B6C/FFFFFF?text=AU",
            languages="English, Swahili",
            education="MBChB from University of Nairobi; Master of Medicine in Family Medicine.",
            certifications="Kenya Medical Practitioners Board Certified; Advanced Cardiac Life Support (ACLS).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2,3",
            bio="Dr. User is a dedicated general practitioner with extensive experience in family medicine and preventive care.",
            available=True,
            rating=4.5,
            reviews=0,
            phone="0700000001",
            years_practice=10,
            working_hours="Mon-Fri 8AM-5PM",
            fee=1500,
            duration=20,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Faith",
            last_name="Wanjiku",
            email="faith.wanjiku@example.com",
            specialty="Cardiology",
            specialties="Heart Health,Cardiac Rehabilitation,Preventive Cardiology,Echocardiography",
            profile_image="https://placehold.co/150x150/0F7B6C/FFFFFF?text=FW",
            languages="English, Swahili, French",
            education="MD from University of Nairobi; Cardiology Fellowship at Kenyatta National Hospital; MPH in Cardiovascular Epidemiology.",
            certifications="Fellow of the College of Physicians (FCP- Cardiology); Certified Cardiac Sonographer; Advanced Cardiac Life Support (ACLS).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Wanjiku is a highly experienced cardiologist with over 12 years of clinical practice.",
            available=True,
            rating=4.8,
            reviews=0,
            phone="0767890123",
            years_practice=12,
            working_hours="Mon-Fri 8AM-4PM",
            fee=2500,
            duration=30,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="George",
            last_name="Kamau",
            email="george.kamau@example.com",
            specialty="Pediatrics",
            specialties="Child Wellness,Immunizations,Growth Monitoring,Behavioral Health",
            profile_image="https://placehold.co/150x150/2563EB/FFFFFF?text=GK",
            languages="English, Swahili",
            education="MBChB from Moi University; Pediatric Residency at Aga Khan University Hospital; Diploma in Child Health.",
            certifications="Kenya Pediatric Society Member; Advanced Pediatric Life Support (APLS); Neonatal Resuscitation Program (NRP).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,3",
            bio="Dr. Kamau is a dedicated pediatrician with 8 years of experience in child wellness and development.",
            available=True,
            rating=4.5,
            reviews=0,
            phone="0778901234",
            years_practice=8,
            working_hours="Mon-Fri 9AM-5PM",
            fee=2000,
            duration=20,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Hannah",
            last_name="Chebet",
            email="hannah.chebet@example.com",
            specialty="Dermatology",
            specialties="Skin Cancer Screening,Laser Therapy,Cosmetic Dermatology,Acne Treatment",
            profile_image="https://placehold.co/150x150/DB2777/FFFFFF?text=HC",
            languages="English, Swahili, French, German",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; MSc in Dermatological Sciences.",
            certifications="American Academy of Dermatology International Member; Certified Laser Safety Officer; Fellow of the Royal Society of Medicine.",
            working_days="Tue-Sat",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Chebet is a board-certified dermatologist with 6 years of specialized experience.",
            available=False,
            rating=4.6,
            reviews=0,
            phone="0789012345",
            years_practice=6,
            working_hours="Tue-Sat 10AM-4PM",
            fee=3000,
            duration=30,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Paul",
            last_name="Ndirangu",
            email="paul.ndirangu@example.com",
            specialty="Neurology",
            specialties="Stroke Management,Epilepsy,Multiple Sclerosis,Neurodegenerative Diseases",
            profile_image="https://placehold.co/150x150/059669/FFFFFF?text=PN",
            languages="English, Swahili",
            education="MD from University of Nairobi; Neurology Residency at Kenyatta National Hospital; Fellowship in Stroke Medicine.",
            certifications="Board Certified Neurologist; Fellow of the World Stroke Organization; Certified in Neuroimaging Interpretation.",
            working_days="Mon-Wed-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Ndirangu is a renowned neurologist with 10 years of expertise.",
            available=True,
            rating=4.7,
            reviews=0,
            phone="0711000001",
            years_practice=10,
            working_hours="Mon-Wed-Fri 8AM-3PM",
            fee=3500,
            duration=45,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Mary",
            last_name="Atieno",
            email="mary.atieno@example.com",
            specialty="Orthopedics",
            specialties="Joint Replacement,Sports Medicine,Trauma Surgery,Minimally Invasive Procedures",
            profile_image="https://placehold.co/150x150/D97706/FFFFFF?text=MA",
            languages="English, Swahili, Italian",
            education="MBChB from University of Nairobi; Orthopedic Surgery Residency at Aga Khan University; Fellowship in Joint Replacement in Milan.",
            certifications="Fellow of the Royal College of Surgeons (FRCS); AO Trauma Certified; Minimally Invasive Surgery Certified.",
            working_days="Mon-Thu",
            consultation_type="Physical",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Atieno is a leading orthopedic surgeon with 15 years of experience.",
            available=True,
            rating=4.9,
            reviews=0,
            phone="0711000002",
            years_practice=15,
            working_hours="Mon-Thu 7AM-3PM",
            fee=4000,
            duration=40,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="James",
            last_name="Kariuki",
            email="james.kariuki@example.com",
            specialty="General Practice",
            specialties="Preventive Medicine,Family Healthcare,Chronic Disease Management,Health Screenings",
            profile_image="https://placehold.co/150x150/4F46E5/FFFFFF?text=JK",
            languages="English, Swahili",
            education="MBChB from University of Nairobi; Master of Medicine in Family Medicine; Diploma in Public Health.",
            certifications="Kenya Medical Practitioners Board Certified; Advanced Cardiac Life Support (ACLS); Travel Medicine Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2",
            bio="Dr. Kariuki is a compassionate general practitioner with 5 years of experience.",
            available=True,
            rating=4.4,
            reviews=0,
            phone="0711000003",
            years_practice=5,
            working_hours="Mon-Fri 8AM-5PM",
            fee=1500,
            duration=15,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Grace",
            last_name="Muthoni",
            email="grace.muthoni@example.com",
            specialty="Pediatrics",
            specialties="Child Development,Early Intervention,Growth Monitoring,Behavioral Health",
            profile_image="https://placehold.co/150x150/EC4899/FFFFFF?text=GM",
            languages="English, Swahili, Kikuyu",
            education="MBChB from University of Nairobi; Pediatric Residency at Kenyatta National Hospital; Masters in Child Development.",
            certifications="Kenya Pediatric Society Member; Developmental Behavioral Pediatrics Certified; Breastfeeding Counselor Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2,3",
            bio="Dr. Muthoni is a caring pediatrician with 7 years of focused experience.",
            available=True,
            rating=4.6,
            reviews=0,
            phone="0711000004",
            years_practice=7,
            working_hours="Mon-Fri 9AM-4PM",
            fee=2200,
            duration=25,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Peter",
            last_name="Ochieng",
            email="peter.ochieng@example.com",
            specialty="Cardiology",
            specialties="Heart Failure Management,Interventional Cardiology,Cardiac Catheterization,Preventive Cardiology",
            profile_image="https://placehold.co/150x150/0891B2/FFFFFF?text=PO",
            languages="English, Swahili, Luo",
            education="MD from University of Nairobi; Cardiology Residency at Aga Khan University; Fellowship in Interventional Cardiology.",
            certifications="Fellow of the American College of Cardiology (FACC); Certified Interventional Cardiologist; Bariatric Endoscopy Certified.",
            working_days="Mon-Tue-Thu",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2",
            bio="Dr. Ochieng is an experienced cardiologist with 11 years of specialized practice.",
            available=False,
            rating=4.8,
            reviews=0,
            phone="0711000005",
            years_practice=11,
            working_hours="Mon-Tue-Thu 8AM-4PM",
            fee=3200,
            duration=35,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Susan",
            last_name="Wairimu",
            email="susan.wairimu@example.com",
            specialty="Dermatology",
            specialties="Skin Cancer Screening,Psoriasis Treatment,Vitiligo Care,Acne Management",
            profile_image="https://placehold.co/150x150/10B981/FFFFFF?text=SW",
            languages="English, Swahili, Kikuyu",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; Clinical Fellowship in Dermatopathology.",
            certifications="American Academy of Dermatology Fellow; Dermatopathology Board Certified; Mohs Surgery Trained.",
            working_days="Wed-Sat",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2,3",
            bio="Dr. Wairimu is a skilled dermatologist with 9 years of experience.",
            available=True,
            rating=4.7,
            reviews=0,
            phone="0711000006",
            years_practice=9,
            working_hours="Wed-Sat 10AM-5PM",
            fee=2800,
            duration=30,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="John",
            last_name="Kipkoech",
            email="john.kipkoech@example.com",
            specialty="General Practice",
            specialties="Family Medicine,Diabetes Management,Hypertension Care,Obesity Treatment",
            profile_image="https://placehold.co/150x150/6366F1/FFFFFF?text=JK",
            languages="English, Swahili, Kalenjin",
            education="MBChB from Moi University; Master of Medicine in Family Medicine; Executive MBA in Healthcare Management.",
            certifications="Kenya Medical Practitioners Board Certified; Diabetes Educator Certified; Hypertension Specialist Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2,3",
            bio="Dr. Kipkoech is a dedicated GP with 6 years of strong focus on family medicine.",
            available=True,
            rating=4.5,
            reviews=0,
            phone="0711000007",
            years_practice=6,
            working_hours="Mon-Fri 8AM-4PM",
            fee=1800,
            duration=20,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Lucy",
            last_name="Cherotich",
            email="lucy.cherotich@example.com",
            specialty="Orthopedics",
            specialties="Sports Injuries,Musculoskeletal Disorders,Ligament Tears,Rehabilitation",
            profile_image="https://placehold.co/150x150/F59E0B/FFFFFF?text=LC",
            languages="English, Swahili, Kalenjin",
            education="MBChB from University of Nairobi; Orthopedic Surgery Residency at Aga Khan University; Sports Medicine Fellowship in South Africa.",
            certifications="Fellow of the Royal College of Surgeons (FRCS); Sports Medicine Certified; Orthopedic Trauma Association Member.",
            working_days="Mon-Fri",
            consultation_type="Physical",
            verification_status="Verified",
            hospital_ids="3",
            bio="Dr. Cherotich is an accomplished orthopedic specialist with 12 years of experience.",
            available=True,
            rating=4.9,
            reviews=0,
            phone="0711000008",
            years_practice=12,
            working_hours="Mon-Fri 7AM-2PM",
            fee=3800,
            duration=40,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Mark",
            last_name="Sang",
            email="mark.sang@example.com",
            specialty="Neurology",
            specialties="Stroke Care,Neurocritical Care,Epilepsy Management,Parkinson's Disease",
            profile_image="https://placehold.co/150x150/14B8A6/FFFFFF?text=MS",
            languages="English, Swahili",
            education="MD from University of Nairobi; Neurology Residency at Kenyatta National Hospital; Fellowship in Neurocritical Care.",
            certifications="Board Certified Neurologist; Neurocritical Care Society Member; Certified in Neurointensive Care.",
            working_days="Tue-Thu",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="3",
            bio="Dr. Sang is a skilled neurologist with 8 years of experience in stroke care.",
            available=True,
            rating=4.6,
            reviews=0,
            phone="0711000009",
            years_practice=8,
            working_hours="Tue-Thu 9AM-4PM",
            fee=3400,
            duration=45,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Nancy",
            last_name="Jeptoo",
            email="nancy.jeptoo@example.com",
            specialty="Pediatrics",
            specialties="Newborn Care,Neonatal Medicine,Premature Birth Care,Congenital Conditions",
            profile_image="https://placehold.co/150x150/F472B6/FFFFFF?text=NJ",
            languages="English, Swahili, Kalenjin",
            education="MBChB from Moi University; Pediatric Residency at Aga Khan University; Neonatal-Perinatal Medicine Fellowship.",
            certifications="Kenya Pediatric Society Fellow; Neonatal Resuscitation Program (NRP) Instructor; Breastfeeding Specialist Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="3",
            bio="Dr. Jeptoo is a board-certified pediatrician with 10 years of specialized experience.",
            available=True,
            rating=4.8,
            reviews=0,
            phone="0711000010",
            years_practice=10,
            working_hours="Mon-Fri 8AM-3PM",
            fee=2300,
            duration=25,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Daniel",
            last_name="Kemboi",
            email="daniel.kemboi@example.com",
            specialty="Cardiology",
            specialties="Preventive Cardiology,Risk Assessment,Lifestyle Modification,Cardiac Wellness",
            profile_image="https://placehold.co/150x150/0E7490/FFFFFF?text=DK",
            languages="English, Swahili, Kalenjin",
            education="MD from Moi University; Cardiology Residency at Aga Khan University; Masters in Preventive Cardiology.",
            certifications="Preventive Cardiology Certified; Fellow of the American Heart Association; Cardiac Rehabilitation Specialist.",
            working_days="Mon-Wed-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="3,1",
            bio="Dr. Kemboi is a prevention-focused cardiologist with 9 years of experience.",
            available=True,
            rating=4.7,
            reviews=0,
            phone="0711000011",
            years_practice=9,
            working_hours="Mon-Wed-Fri 8AM-4PM",
            fee=2900,
            duration=35,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=admin_user.id,
            first_name="Sarah",
            last_name="Jepchirchir",
            email="sarah.jepchirchir@example.com",
            specialty="Dermatology",
            specialties="Cosmetic Dermatology,Skin Rejuvenation,Anti-Aging Treatments,Reconstructive Procedures",
            profile_image="https://placehold.co/150x150/7C3AED/FFFFFF?text=SJ",
            languages="English, Swahili, Kalenjin",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; Cosmetic Surgery Fellowship.",
            certifications="American Academy of Dermatology Fellow; Cosmetic Dermatology Certified; Reconstructive Surgery Board Certified.",
            working_days="Tue-Sat",
            consultation_type="Online",
            verification_status="Verified",
            hospital_ids="3,1",
            bio="Dr. Jepchirchir is an expert dermatologist with 13 years of experience.",
            available=False,
            rating=4.9,
            reviews=0,
            phone="0711000012",
            years_practice=13,
            working_hours="Tue-Sat 11AM-5PM",
            fee=3200,
            duration=30,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
    ]
    db.session.add_all(doctors)
    db.session.commit()
    print(f"Seeded {len(doctors)} doctors.")

    patients = [
        Patient(
            user_id=admin_user.id,
            first_name="John",
            last_name="Mwangi",
            email="john.mwangi@example.com",
            phone="0723456789",
            dob=date(1985, 3, 15),
            gender="Male",
            address="301 Nairobi, Kenya",
        ),
        Patient(
            user_id=admin_user.id,
            first_name="Sarah",
            last_name="Ochieng",
            email="sarah.ochieng@example.com",
            phone="0734567890",
            dob=date(1990, 7, 22),
            gender="Female",
            address="00200 Nairobi, Kenya",
        ),
        Patient(
            user_id=admin_user.id,
            first_name="David",
            last_name="Mutiso",
            email="david.mutiso@example.com",
            phone="0745678901",
            dob=date(1978, 11, 5),
            gender="Male",
            address="501 Mombasa, Kenya",
        ),
        Patient(
            user_id=admin_user.id,
            first_name="Grace",
            last_name="Kariuki",
            email="grace.kariuki@example.com",
            phone="0756789012",
            dob=date(1995, 4, 18),
            gender="Female",
            address="201 Kisumu, Kenya",
        ),
        Patient(
            user_id=admin_user.id,
            first_name="Michael",
            last_name="Omondi",
            email="michael.omondi@example.com",
            phone="0767890123",
            dob=date(1982, 9, 30),
            gender="Male",
            address="101 Nakuru, Kenya",
        ),
    ]
    db.session.add_all(patients)
    db.session.commit()
    print(f"Seeded {len(patients)} patients.")

    now = datetime.now()
    today = now.date()
    appointments = [
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today, datetime.min.time()),
            appointment_time=time(9, 0),
            status='Scheduled',
            notes='Routine checkup',
        ),
        Appointment(
            patient_id=patients[1].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today, datetime.min.time()),
            appointment_time=time(10, 30),
            status='Scheduled',
            notes='Follow-up for hypertension',
        ),
        Appointment(
            patient_id=patients[2].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today, datetime.min.time()),
            appointment_time=time(11, 30),
            status='Completed',
            notes='Annual physical examination',
        ),
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[1].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today, datetime.min.time()),
            appointment_time=time(14, 0),
            status='Pending',
            notes='Cardiac screening',
        ),
        Appointment(
            patient_id=patients[3].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today, datetime.min.time()),
            appointment_time=time(15, 30),
            status='Cancelled',
            notes='Patient cancelled due to illness',
        ),
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today - __import__('datetime').timedelta(days=2), datetime.min.time()),
            appointment_time=time(10, 0),
            status='Completed',
            notes='Routine checkup',
        ),
        Appointment(
            patient_id=patients[1].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today + __import__('datetime').timedelta(days=1), datetime.min.time()),
            appointment_time=time(9, 30),
            status='Scheduled',
            notes='Follow-up appointment',
        ),
        Appointment(
            patient_id=patients[2].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today + __import__('datetime').timedelta(days=2), datetime.min.time()),
            appointment_time=time(14, 0),
            status='Scheduled',
            notes='Blood pressure check',
        ),
        Appointment(
            patient_id=patients[4].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today + __import__('datetime').timedelta(days=3), datetime.min.time()),
            appointment_time=time(11, 0),
            status='Pending',
            notes='New patient consultation',
        ),
        Appointment(
            patient_id=patients[3].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime.combine(today + __import__('datetime').timedelta(days=5), datetime.min.time()),
            appointment_time=time(10, 0),
            status='Scheduled',
            notes='Medication review',
        ),
    ]
    db.session.add_all(appointments)
    db.session.commit()
    print(f"Seeded {len(appointments)} appointments.")

    medical_records = [
        MedicalRecord(
            appointment_id=appointments[2].id,
            doctor_id=doctors[0].id,
            patient_id=patients[0].id,
            diagnosis='Malaria',
            symptoms='Fever, headache, body aches, fatigue',
            prescription='Artemether Lumefantrine (Coartem) - 4 tablets initial dose, then 2 tablets twice daily for 3 days',
            treatment_plan='Complete full course of antimalarial treatment, increase water intake, rest',
            lab_requests='Complete Blood Count (CBC), Malaria RDT',
            follow_up_date=datetime.combine(today + __import__('datetime').timedelta(days=7), datetime.min.time()),
            additional_notes='Increase water intake. Take medication with food. Return if symptoms worsen.',
        ),
        MedicalRecord(
            appointment_id=appointments[5].id,
            doctor_id=doctors[0].id,
            patient_id=patients[0].id,
            diagnosis='Hypertension',
            symptoms='Occasional headaches, no chest pain',
            prescription='Lisinopril 10mg daily, take in the morning',
            treatment_plan='Monitor blood pressure weekly, follow DASH diet, limit sodium intake',
            lab_requests='Comprehensive metabolic panel, lipid profile',
            follow_up_date=datetime.combine(today + __import__('datetime').timedelta(days=14), datetime.min.time()),
            additional_notes='Blood pressure was 145/92. Lifestyle modifications recommended.',
        ),
        MedicalRecord(
            appointment_id=appointments[0].id,
            doctor_id=doctors[0].id,
            patient_id=patients[0].id,
            diagnosis='General health checkup - Normal',
            symptoms='No active complaints',
            prescription='Multivitamin daily, Omega-3 supplements',
            treatment_plan='Maintain current health regimen, annual checkup recommended',
            lab_requests='None at this time',
            follow_up_date=None,
            additional_notes='All vitals normal. Patient is in good health.',
        ),
    ]
    db.session.add_all(medical_records)
    db.session.commit()
    print(f"Seeded {len(medical_records)} medical records.")

    prescriptions = [
        Prescription(
            medical_record_id=medical_records[0].id,
            appointment_id=appointments[2].id,
            doctor_id=doctors[0].id,
            patient_id=patients[0].id,
            medicine='Artemether Lumefantrine',
            dosage='500mg',
            frequency='Twice Daily',
            duration='3 Days',
            instructions='Take with food. Complete the full course.',
        ),
        Prescription(
            medical_record_id=medical_records[1].id,
            appointment_id=appointments[5].id,
            doctor_id=doctors[0].id,
            patient_id=patients[0].id,
            medicine='Lisinopril',
            dosage='10mg',
            frequency='Once Daily',
            duration='30 Days',
            instructions='Take in the morning. Monitor blood pressure.',
        ),
        Prescription(
            medical_record_id=medical_records[2].id,
            appointment_id=appointments[0].id,
            doctor_id=doctors[0].id,
            patient_id=patients[0].id,
            medicine='Multivitamin',
            dosage='1 tablet',
            frequency='Once Daily',
            duration='90 Days',
            instructions='Take with breakfast.',
        ),
    ]
    db.session.add_all(prescriptions)
    db.session.commit()
    print(f"Seeded {len(prescriptions)} prescriptions.")

    days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    schedules = [
        DoctorSchedule(doctor_id=doctors[0].id, day_of_week=0, start_time=time(8, 0), end_time=time(17, 0)),
        DoctorSchedule(doctor_id=doctors[0].id, day_of_week=1, start_time=time(8, 0), end_time=time(17, 0)),
        DoctorSchedule(doctor_id=doctors[0].id, day_of_week=2, start_time=time(8, 0), end_time=time(17, 0)),
        DoctorSchedule(doctor_id=doctors[0].id, day_of_week=3, start_time=time(8, 0), end_time=time(17, 0)),
        DoctorSchedule(doctor_id=doctors[0].id, day_of_week=4, start_time=time(8, 0), end_time=time(17, 0)),
        DoctorSchedule(doctor_id=doctors[0].id, day_of_week=2, start_time=time(13, 0), end_time=time(14, 0), is_break=True),
    ]
    db.session.add_all(schedules)
    db.session.commit()
    print(f"Seeded {len(schedules)} schedule entries.")

    reviews = [
        Review(
            appointment_id=appointments[2].id,
            patient_id=patients[0].id,
            doctor_id=doctors[0].id,
            rating=5,
            comment='Excellent doctor. Very thorough and caring.',
        ),
        Review(
            appointment_id=appointments[5].id,
            patient_id=patients[0].id,
            doctor_id=doctors[0].id,
            rating=4,
            comment='Dr. User was very professional and explained everything clearly.',
        ),
    ]
    db.session.add_all(reviews)
    db.session.commit()
    print(f"Seeded {len(reviews)} reviews.")

    doctors[0].rating = 4.5
    doctors[0].reviews = 2
    db.session.commit()

    notifications = [
        Notification(
            doctor_id=doctors[0].id,
            type='appointment_booked',
            title='New appointment booked',
            message='John Mwangi has booked a new appointment for today at 9:00 AM.',
            related_appointment_id=appointments[0].id,
            related_patient_id=patients[0].id,
        ),
        Notification(
            doctor_id=doctors[0].id,
            type='appointment_cancelled',
            title='Appointment cancelled',
            message='Sarah Ochieng cancelled their appointment scheduled for today at 15:30.',
            related_appointment_id=appointments[4].id,
            related_patient_id=patients[3].id,
        ),
        Notification(
            doctor_id=doctors[0].id,
            type='followup_reminder',
            title='Follow-up reminder',
            message='John Mwangi has a follow-up appointment in 3 days.',
            related_appointment_id=appointments[7].id,
            related_patient_id=patients[2].id,
        ),
    ]
    db.session.add_all(notifications)
    db.session.commit()
    print(f"Seeded {len(notifications)} notifications.")

    documents = [
        DoctorDocument(
            doctor_id=doctors[0].id,
            doc_type='medical_license',
            title='Medical License - Kenya Medical Practitioners Board',
            file_url='https://example.com/license.pdf',
            file_name='medical_license.pdf',
            verified=True,
        ),
        DoctorDocument(
            doctor_id=doctors[0].id,
            doc_type='certificate',
            title='Advanced Cardiac Life Support (ACLS) Certification',
            file_url='https://example.com/acls.pdf',
            file_name='acls_certificate.pdf',
            verified=True,
        ),
        DoctorDocument(
            doctor_id=doctors[0].id,
            doc_type='cv',
            title='Curriculum Vitae',
            file_url='https://example.com/cv.pdf',
            file_name='dr_user_cv.pdf',
            verified=True,
        ),
    ]
    db.session.add_all(documents)
    db.session.commit()
    print(f"Seeded {len(documents)} documents.")

    print("Done seeding!")