from datetime import date, datetime, time

from app import app
from auth import hash_password
from model import Appointment, Doctor, Hospital, Patient, Review, User, db
from sqlalchemy import text

with app.app_context():
    db.session.query(Review).delete()
    db.session.query(Appointment).delete()
    db.session.query(Doctor).delete()
    db.session.query(Patient).delete()
    db.session.query(Hospital).delete()
    db.session.query(User).delete()
    db.session.commit()

    db.session.execute(text("ALTER SEQUENCE users_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE patients_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE doctors_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE hospitals_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE appointments_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE reviews_id_seq RESTART WITH 1"))
    db.session.commit()

    users = [
        User(
            first_name="Alice",
            last_name="Johnson",
            email="alice.johnson@example.com",
            phone="0712345678",
            password=hash_password("password123"),
        ),
        User(
            first_name="Brian",
            last_name="Mwangi",
            email="brian.mwangi@example.com",
            phone="0723456789",
            password=hash_password("password123"),
        ),
        User(
            first_name="Carol",
            last_name="Ndegwa",
            email="carol.ndegwa@example.com",
            phone="0734567890",
            password=hash_password("password123"),
        ),
        User(
            first_name="David",
            last_name="Otieno",
            email="david.otieno@example.com",
            phone="0745678901",
            password=hash_password("password123"),
        ),
        User(
            first_name="George",
            last_name="Kamau",
            email="george.kamau@example.com",
            phone="0778901234",
            password=hash_password("password123"),
        ),
        User(
            first_name="Hannah",
            last_name="Chebet",
            email="hannah.chebet@example.com",
            phone="0789012345",
            password=hash_password("password123"),
        ),
        User(
            first_name="Ian",
            last_name="Mutua",
            email="ian.mutua@example.com",
            phone="0790123456",
            password=hash_password("password123"),
        ),
        User(
            first_name="Jane",
            last_name="Achieng",
            email="jane.achieng@example.com",
            phone="0701234567",
            password=hash_password("password123"),
        ),
        User(
            first_name="Paul",
            last_name="Ndirangu",
            email="paul.ndirangu@example.com",
            phone="0711000001",
            password=hash_password("password123"),
        ),
        User(
            first_name="Mary",
            last_name="Atieno",
            email="mary.atieno@example.com",
            phone="0711000002",
            password=hash_password("password123"),
        ),
        User(
            first_name="James",
            last_name="Kariuki",
            email="james.kariuki@example.com",
            phone="0711000003",
            password=hash_password("password123"),
        ),
        User(
            first_name="Grace",
            last_name="Muthoni",
            email="grace.muthoni@example.com",
            phone="0711000004",
            password=hash_password("password123"),
        ),
        User(
            first_name="Peter",
            last_name="Ochieng",
            email="peter.ochieng@example.com",
            phone="0711000005",
            password=hash_password("password123"),
        ),
        User(
            first_name="Susan",
            last_name="Wairimu",
            email="susan.wairimu@example.com",
            phone="0711000006",
            password=hash_password("password123"),
        ),
        User(
            first_name="John",
            last_name="Kipkoech",
            email="john.kipkoech@example.com",
            phone="0711000007",
            password=hash_password("password123"),
        ),
        User(
            first_name="rucy",
            last_name="Cherotich",
            email="lucy.cherotich@example.com",
            phone="0711000008",
            password=hash_password("password123"),
        ),
        User(
            first_name="Mark",
            last_name="Sang",
            email="mark.sang@example.com",
            phone="0711000009",
            password=hash_password("password123"),
        ),
        User(
            first_name="Nancy",
            last_name="Jeptoo",
            email="nancy.jeptoo@example.com",
            phone="0711000010",
            password=hash_password("password123"),
        ),
        User(
            first_name="Daniel",
            last_name="Kemboi",
            email="daniel.kemboi@example.com",
            phone="0711000011",
            password=hash_password("password123"),
        ),
        User(
            first_name="Sarah",
            last_name="Jepchirchir",
            email="sarah.jepchirchir@example.com",
            phone="0711000012",
            password=hash_password("password123"),
        ),
    ]
    db.session.add_all(users)
    db.session.commit()
    print(f"Seeded {len(users)} users.")

    patients = [
        Patient(
            user_id=users[0].id,
            first_name="Alice",
            last_name="Johnson",
            email="alice.johnson@example.com",
            dob=date(1992, 4, 15),
            gender="Female",
            address="14 Kijabe Street, Nairobi",
            phone="0712345678",
        ),
        Patient(
            user_id=users[1].id,
            first_name="Brian",
            last_name="Mwangi",
            email="brian.mwangi@example.com",
            dob=date(1988, 11, 2),
            gender="Male",
            address="22 Mombasa Road, Nairobi",
            phone="0723456789",
        ),
        Patient(
            user_id=users[2].id,
            first_name="Carol",
            last_name="Ndegwa",
            email="carol.ndegwa@example.com",
            dob=date(1995, 7, 21),
            gender="Female",
            address="9 Kiambu Lane, Kiambu",
            phone="0734567890",
        ),
        Patient(
            user_id=users[3].id,
            first_name="David",
            last_name="Otieno",
            email="david.otieno@example.com",
            dob=date(1985, 1, 30),
            gender="Male",
            address="5 Kisumu Avenue, Kisumu",
            phone="0745678901",
        ),
        Patient(
            user_id=users[4].id,
            first_name="Eva",
            last_name="Kipchoge",
            email="eva.kipchoge@example.com",
            dob=date(2000, 9, 10),
            gender="Female",
            address="31 Eldoret Road, Eldoret",
            phone="0756789012",
        ),
    ]
    db.session.add_all(patients)
    db.session.commit()
    print(f"Seeded {len(patients)} patients.")

    hospitals = [
        Hospital(
            name="Nairobi General Hospital",
            address="001 Hospital Hill, Nairobi",
            phone="0201234567",
            email="info@nairobigenhospital.co.ke",
            website="https://nairobigenhospital.co.ke",
        ),
        Hospital(
            name="Mombasa Medical Centre",
            address="78 Nyali Bridge Road, Mombasa",
            phone="0412345678",
            email="info@mombasamedical.co.ke",
            website="https://mombasamedical.co.ke",
        ),
        Hospital(
            name="Kisumu County Referral",
            address="12 Lake Basin Road, Kisumu",
            phone="0571234567",
            email="info@kisumuhospital.co.ke",
            website="https://kisumuhospital.co.ke",
        ),
    ]
    db.session.add_all(hospitals)
    db.session.commit()
    print(f"Seeded {len(hospitals)} hospitals.")

    doctors = [
        Doctor(
            user_id=users[5].id,
            first_name="Faith",
            last_name="Wanjiku",
            email="faith.wanjiku@example.com",
            specialty="Cardiology",
            specialties="Heart Health,Cardiac Rehabilitation,Preventive Cardiology,Echocardiography",
            profile_image="https://placehold.co/150x150/0F7B6C/FFFFFF?text=FW",
            languages="English, Swahili, French",
            education="MD from University of Nairobi; Cardiology Fellowship at Kenyatta National Hospital; MPH in Cardiovascular Epidemiology.",
            certifications="Fellow of the College of Physicians (FCP- Cardiology); Certified Cardiac Sonographer; Advanced Cardiac Life Support (ACLS).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Wanjiku is a highly experienced cardiologist with over 12 years of clinical practice. She specializes in preventive cardiology, heart failure management, and cardiac rehabilitation. Her patient-centered approach combines advanced medical expertise with compassionate care, ensuring each patient receives personalized treatment plans. She has performed over 500 successful cardiac procedures and is committed to advancing cardiovascular health in the community through education and early intervention strategies.",
            available=True,
            rating=4.8,
            reviews=127,
            phone="0767890123",
            years_practice=12,
            working_hours="Mon-Fri 8AM-4PM",
            fee=2500,
            duration=30,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[6].id,
            first_name="George",
            last_name="Kamau",
            email="george.kamau@example.com",
            specialty="Pediatrics",
            specialties="Child Wellness,Immunizations,Growth Monitoring,Behavioral Health",
            profile_image="https://placehold.co/150x150/2563EB/FFFFFF?text=GK",
            languages="English, Swahili",
            education="MBChB from Moi University; Pediatric Residency at Aga Khan University Hospital; Diploma in Child Health.",
            certifications="Kenya Pediatric Society Member; Advanced Pediatric Life Support (APLS); Neonatal Resuscitation Program (NRP).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,3",
            bio="Dr. Kamau is a dedicated pediatrician with 8 years of experience in child wellness and development. He believes in building lasting relationships with his young patients and their families, providing comprehensive care from newborns to adolescents. His gentle approach and extensive knowledge in childhood immunizations, growth monitoring, and behavioral health make him a trusted choice for parents. He actively promotes child health awareness through community outreach programs and school health initiatives.",
            available=True,
            rating=4.5,
            reviews=89,
            phone="0778901234",
            years_practice=8,
            working_hours="Mon-Fri 9AM-5PM",
            fee=2000,
            duration=20,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[7].id,
            first_name="Hannah",
            last_name="Chebet",
            email="hannah.chebet@example.com",
            specialty="Dermatology",
            specialties="Skin Cancer Screening,Laser Therapy,Cosmetic Dermatology,Acne Treatment",
            profile_image="https://placehold.co/150x150/DB2777/FFFFFF?text=HC",
            languages="English, Swahili, French, German",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; MSc in Dermatological Sciences.",
            certifications="American Academy of Dermatology International Member; Certified Laser Safety Officer; Fellow of the Royal Society of Medicine.",
            working_days="Tue-Sat",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Chebet is a board-certified dermatologist with 6 years of specialized experience in medical and cosmetic dermatology. She is skilled in diagnosing and treating a wide range of skin conditions, from acne and eczema to skin cancer screenings. Her modern clinic offers advanced treatments including laser therapy, chemical peels, and Botox. Dr. Chebet is passionate about patient education and believes in empowering individuals to maintain healthy skin through proper skincare routines and sun protection.",
            available=False,
            rating=4.6,
            reviews=64,
            phone="0789012345",
            years_practice=6,
            working_hours="Tue-Sat 10AM-4PM",
            fee=3000,
            duration=30,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[10].id,
            first_name="Paul",
            last_name="Ndirangu",
            email="paul.ndirangu@example.com",
            specialty="Neurology",
            specialties="Stroke Management,Epilepsy,Multiple Sclerosis,Neurodegenerative Diseases",
            profile_image="https://placehold.co/150x150/059669/FFFFFF?text=PN",
            languages="English, Swahili",
            education="MD from University of Nairobi; Neurology Residency at Kenyatta National Hospital; Fellowship in Stroke Medicine.",
            certifications="Board Certified Neurologist; Fellow of the World Stroke Organization; Certified in Neuroimaging Interpretation.",
            working_days="Mon-Wed-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Ndirangu is a renowned neurologist with 10 years of expertise in diagnosing and treating complex brain and nerve disorders. He specializes in stroke management, epilepsy, multiple sclerosis, and neurodegenerative diseases. Using cutting-edge diagnostic technology and evidence-based treatment protocols, he provides comprehensive care for patients with neurological conditions. Dr. Ndirangu is also involved in clinical research and regularly contributes to medical journals, advancing the field of neurology in Kenya.",
            available=True,
            rating=4.7,
            reviews=103,
            phone="0711000001",
            years_practice=10,
            working_hours="Mon-Wed-Fri 8AM-3PM",
            fee=3500,
            duration=45,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[11].id,
            first_name="Mary",
            last_name="Atieno",
            email="mary.atieno@example.com",
            specialty="Orthopedics",
            specialties="Joint Replacement,Sports Medicine,Trauma Surgery,Minimally Invasive Procedures",
            profile_image="https://placehold.co/150x150/D97706/FFFFFF?text=MA",
            languages="English, Swahili, Italian",
            education="MBChB from University of Nairobi; Orthopedic Surgery Residency at Aga Khan University; Fellowship in Joint Replacement in Milan.",
            certifications="Fellow of the Royal College of Surgeons (FRCS); AO Trauma Certified; Minimally Invasive Surgery Certified.",
            working_days="Mon-Thu",
            consultation_type="Physical",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Atieno is a leading orthopedic surgeon with 15 years of experience in bone and joint care. She specializes in joint replacement surgeries, sports medicine, and trauma surgery. Her surgical precision and innovative techniques have helped hundreds of patients regain mobility and return to active lifestyles. Dr. Atieno is particularly passionate about minimally invasive procedures and has trained surgeons across East Africa. She believes in a holistic approach to orthopedic care, combining surgery with rehabilitation for optimal outcomes.",
            available=True,
            rating=4.9,
            reviews=156,
            phone="0711000002",
            years_practice=15,
            working_hours="Mon-Thu 7AM-3PM",
            fee=4000,
            duration=40,
            hospital_name=hospitals[0].name,            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[12].id,
            first_name="James",
            last_name="Kariuki",
            email="james.kariuki@example.com",
            specialty="General Practice",
            specialties="Preventive Medicine,Family Healthcare,Chronic Disease Management,Health Screenings",
            profile_image="https://placehold.co/150x150/4F46E5/FFFFFF?text=JK",
            languages="English, Swahili",
            education="MBChB from University of Nairobi; Master of Medicine in Family Medicine; Diploma in Public Health.",
            certifications="Kenya Medical Practitioners Board Certified; Advanced Cardiac Life Support (ACLS); Travel Medicine Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2",
            bio="Dr. Kariuki is a compassionate general practitioner with 5 years of experience in preventive medicine and family healthcare. He provides comprehensive medical care for patients of all ages, focusing on disease prevention, health promotion, and chronic disease management. His practice emphasizes building long-term doctor-patient relationships and he is known for his thorough approach to diagnostics. Dr. Kariuki is a strong advocate for community health and regularly conducts free medical camps in underserved areas.",
            available=True,
            rating=4.4,
            reviews=72,
            phone="0711000003",
            years_practice=5,
            working_hours="Mon-Fri 8AM-5PM",
            fee=1500,
            duration=15,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=users[13].id,
            first_name="Grace",
            last_name="Muthoni",
            email="grace.muthoni@example.com",
            specialty="Pediatrics",
            specialties="Child Development,Early Intervention,Growth Monitoring,Behavioral Health",
            profile_image="https://placehold.co/150x150/EC4899/FFFFFF?text=GM",
            languages="English, Swahili, Kikuyu",
            education="MBChB from University of Nairobi; Pediatric Residency at Kenyatta National Hospital; Masters in Child Development.",
            certifications="Kenya Pediatric Society Member; Developmental Behavioral Pediatrics Certified; Breastfeeding Counselor Certified.",
            working_days="Mon-Fri",
