from datetime import date, datetime, time

from app import app
from auth import generate_token, hash_password
from model import Appointment, Doctor, Hospital, MedicalRecord, Patient, Review, User, db
from sqlalchemy import text

with app.app_context():
    db.session.query(Review).delete()
    db.session.query(MedicalRecord).delete()
    db.session.query(Appointment).delete()
    db.session.query(Doctor).delete()
    db.session.query(Patient).delete()
    db.session.query(Hospital).delete()
    db.session.query(User).delete()
    db.session.commit()

    db.session.execute(text("ALTER SEQUENCE users_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE patients_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE doctors_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE hospitals_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE appointments_id_seq RESTART WITH 1"))
    db.session.execute(text("ALTER SEQUENCE reviews_id_seq RESTART WITH 1"))
    db.session.commit()

    admin_user = User(
        first_name="Admin",
        last_name="User",
        email="admin@example.com",
        phone="0700000001",
        password=hash_password("admin123"),
        role="admin",
        token=generate_token(),
    )
    db.session.add(admin_user)
    db.session.commit()
    print(f"Created admin user with id: {admin_user.id}, token: {admin_user.token}")

    users = [
        User(
            first_name="Alice",
            last_name="Johnson",
            email="alice.johnson@example.com",
            phone="0712345678",
            password=hash_password("password123"),
        ),
        User(
            first_name="Brian",
            last_name="Mwangi",
            email="brian.mwangi@example.com",
            phone="0723456789",
            password=hash_password("password123"),
        ),
        User(
            first_name="Carol",
            last_name="Ndegwa",
            email="carol.ndegwa@example.com",
            phone="0734567890",
            password=hash_password("password123"),
        ),
        User(
            first_name="David",
            last_name="Otieno",
            email="david.otieno@example.com",
            phone="0745678901",
            password=hash_password("password123"),
        ),
        User(
            first_name="Eva",
            last_name="Kipchoge",
            email="eva.kipchoge@example.com",
            phone="0756789012",
            password=hash_password("password123"),
        ),
        User(
            first_name="Faith",
            last_name="Wanjiku",
            email="faith.wanjiku@example.com",
            phone="0767890123",
            password=hash_password("password123"),
        ),
        User(
            first_name="George",
            last_name="Kamau",
            email="george.kamau@example.com",
            phone="0778901234",
            password=hash_password("password123"),
        ),
        User(
            first_name="Hannah",
            last_name="Chebet",
            email="hannah.chebet@example.com",
            phone="0789012345",
            password=hash_password("password123"),
        ),
        User(
            first_name="Ian",
            last_name="Mutua",
            email="ian.mutua@example.com",
            phone="0790123456",
            password=hash_password("password123"),
        ),
        User(
            first_name="Jane",
            last_name="Achieng",
            email="jane.achieng@example.com",
            phone="0701234567",
            password=hash_password("password123"),
        ),
        User(
            first_name="Paul",
            last_name="Ndirangu",
            email="paul.ndirangu@example.com",
            phone="0711000001",
            password=hash_password("password123"),
        ),
        User(
            first_name="Mary",
            last_name="Atieno",
            email="mary.atieno@example.com",
            phone="0711000002",
            password=hash_password("password123"),
        ),
        User(
            first_name="James",
            last_name="Kariuki",
            email="james.kariuki@example.com",
            phone="0711000003",
            password=hash_password("password123"),
        ),
        User(
            first_name="Grace",
            last_name="Muthoni",
            email="grace.muthoni@example.com",
            phone="0711000004",
            password=hash_password("password123"),
        ),
        User(
            first_name="Peter",
            last_name="Ochieng",
            email="peter.ochieng@example.com",
            phone="0711000005",
            password=hash_password("password123"),
        ),
        User(
            first_name="Susan",
            last_name="Wairimu",
            email="susan.wairimu@example.com",
            phone="0711000006",
            password=hash_password("password123"),
        ),
        User(
            first_name="John",
            last_name="Kipkoech",
            email="john.kipkoech@example.com",
            phone="0711000007",
            password=hash_password("password123"),
        ),
        User(
            first_name="rucy",
            last_name="Cherotich",
            email="lucy.cherotich@example.com",
            phone="0711000008",
            password=hash_password("password123"),
        ),
        User(
            first_name="Mark",
            last_name="Sang",
            email="mark.sang@example.com",
            phone="0711000009",
            password=hash_password("password123"),
        ),
        User(
            first_name="Nancy",
            last_name="Jeptoo",
            email="nancy.jeptoo@example.com",
            phone="0711000010",
            password=hash_password("password123"),
        ),
        User(
            first_name="Daniel",
            last_name="Kemboi",
            email="daniel.kemboi@example.com",
            phone="0711000011",
            password=hash_password("password123"),
        ),
        User(
            first_name="Sarah",
            last_name="Jepchirchir",
            email="sarah.jepchirchir@example.com",
            phone="0711000012",
            password=hash_password("password123"),
        ),
    ]
    db.session.add_all(users)
    db.session.commit()
    print(f"Seeded {len(users)} users.")

    patients = [
        Patient(
            user_id=users[0].id,
            first_name="Alice",
            last_name="Johnson",
            email="alice.johnson@example.com",
            dob=date(1992, 4, 15),
            gender="Female",
            address="14 Kijabe Street, Nairobi",
            phone="0712345678",
        ),
        Patient(
            user_id=users[1].id,
            first_name="Brian",
            last_name="Mwangi",
            email="brian.mwangi@example.com",
            dob=date(1988, 11, 2),
            gender="Male",
            address="22 Mombasa Road, Nairobi",
            phone="0723456789",
        ),
        Patient(
            user_id=users[2].id,
            first_name="Carol",
            last_name="Ndegwa",
            email="carol.ndegwa@example.com",
            dob=date(1995, 7, 21),
            gender="Female",
            address="9 Kiambu Lane, Kiambu",
            phone="0734567890",
        ),
        Patient(
            user_id=users[3].id,
            first_name="David",
            last_name="Otieno",
            email="david.otieno@example.com",
            dob=date(1985, 1, 30),
            gender="Male",
            address="5 Kisumu Avenue, Kisumu",
            phone="0745678901",
        ),
        Patient(
            user_id=users[4].id,
            first_name="Eva",
            last_name="Kipchoge",
            email="eva.kipchoge@example.com",
            dob=date(2000, 9, 10),
            gender="Female",
            address="31 Eldoret Road, Eldoret",
            phone="0756789012",
        ),
    ]
    db.session.add_all(patients)
    db.session.commit()
    print(f"Seeded {len(patients)} patients.")

    hospitals = [
        Hospital(
            name="Nairobi General Hospital",
            address="001 Hospital Hill, Nairobi",
            phone="0201234567",
            email="info@nairobigenhospital.co.ke",
            website="https://nairobigenhospital.co.ke",
        ),
        Hospital(
            name="Mombasa Medical Centre",
            address="78 Nyali Bridge Road, Mombasa",
            phone="0412345678",
            email="info@mombasamedical.co.ke",
            website="https://mombasamedical.co.ke",
        ),
        Hospital(
            name="Kisumu County Referral",
            address="12 Lake Basin Road, Kisumu",
            phone="0571234567",
            email="info@kisumuhospital.co.ke",
            website="https://kisumuhospital.co.ke",
        ),
    ]
    db.session.add_all(hospitals)
    db.session.commit()
    print(f"Seeded {len(hospitals)} hospitals.")

    doctors = [
        Doctor(
            user_id=users[5].id,
            first_name="Faith",
            last_name="Wanjiku",
            email="faith.wanjiku@example.com",
            specialty="Cardiology",
            specialties="Heart Health,Cardiac Rehabilitation,Preventive Cardiology,Echocardiography",
            profile_image="https://placehold.co/150x150/0F7B6C/FFFFFF?text=FW",
            languages="English, Swahili, French",
            education="MD from University of Nairobi; Cardiology Fellowship at Kenyatta National Hospital; MPH in Cardiovascular Epidemiology.",
            certifications="Fellow of the College of Physicians (FCP- Cardiology); Certified Cardiac Sonographer; Advanced Cardiac Life Support (ACLS).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Wanjiku is a highly experienced cardiologist with over 12 years of clinical practice. She specializes in preventive cardiology, heart failure management, and cardiac rehabilitation. Her patient-centered approach combines advanced medical expertise with compassionate care, ensuring each patient receives personalized treatment plans. She has performed over 500 successful cardiac procedures and is committed to advancing cardiovascular health in the community through education and early intervention strategies.",
            available=True,
            rating=4.8,
            reviews=127,
            phone="0767890123",
            years_practice=12,
            working_hours="Mon-Fri 8AM-4PM",
            fee=2500,
            duration=30,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[6].id,
            first_name="George",
            last_name="Kamau",
            email="george.kamau@example.com",
            specialty="Pediatrics",
            specialties="Child Wellness,Immunizations,Growth Monitoring,Behavioral Health",
            profile_image="https://placehold.co/150x150/2563EB/FFFFFF?text=GK",
            languages="English, Swahili",
            education="MBChB from Moi University; Pediatric Residency at Aga Khan University Hospital; Diploma in Child Health.",
            certifications="Kenya Pediatric Society Member; Advanced Pediatric Life Support (APLS); Neonatal Resuscitation Program (NRP).",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,3",
            bio="Dr. Kamau is a dedicated pediatrician with 8 years of experience in child wellness and development. He believes in building lasting relationships with his young patients and their families, providing comprehensive care from newborns to adolescents. His gentle approach and extensive knowledge in childhood immunizations, growth monitoring, and behavioral health make him a trusted choice for parents. He actively promotes child health awareness through community outreach programs and school health initiatives.",
            available=True,
            rating=4.5,
            reviews=89,
            phone="0778901234",
            years_practice=8,
            working_hours="Mon-Fri 9AM-5PM",
            fee=2000,
            duration=20,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[7].id,
            first_name="Hannah",
            last_name="Chebet",
            email="hannah.chebet@example.com",
            specialty="Dermatology",
            specialties="Skin Cancer Screening,Laser Therapy,Cosmetic Dermatology,Acne Treatment",
            profile_image="https://placehold.co/150x150/DB2777/FFFFFF?text=HC",
            languages="English, Swahili, French, German",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; MSc in Dermatological Sciences.",
            certifications="American Academy of Dermatology International Member; Certified Laser Safety Officer; Fellow of the Royal Society of Medicine.",
            working_days="Tue-Sat",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Chebet is a board-certified dermatologist with 6 years of specialized experience in medical and cosmetic dermatology. She is skilled in diagnosing and treating a wide range of skin conditions, from acne and eczema to skin cancer screenings. Her modern clinic offers advanced treatments including laser therapy, chemical peels, and Botox. Dr. Chebet is passionate about patient education and believes in empowering individuals to maintain healthy skin through proper skincare routines and sun protection.",
            available=False,
            rating=4.6,
            reviews=64,
            phone="0789012345",
            years_practice=6,
            working_hours="Tue-Sat 10AM-4PM",
            fee=3000,
            duration=30,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[10].id,
            first_name="Paul",
            last_name="Ndirangu",
            email="paul.ndirangu@example.com",
            specialty="Neurology",
            specialties="Stroke Management,Epilepsy,Multiple Sclerosis,Neurodegenerative Diseases",
            profile_image="https://placehold.co/150x150/059669/FFFFFF?text=PN",
            languages="English, Swahili",
            education="MD from University of Nairobi; Neurology Residency at Kenyatta National Hospital; Fellowship in Stroke Medicine.",
            certifications="Board Certified Neurologist; Fellow of the World Stroke Organization; Certified in Neuroimaging Interpretation.",
            working_days="Mon-Wed-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Ndirangu is a renowned neurologist with 10 years of expertise in diagnosing and treating complex brain and nerve disorders. He specializes in stroke management, epilepsy, multiple sclerosis, and neurodegenerative diseases. Using cutting-edge diagnostic technology and evidence-based treatment protocols, he provides comprehensive care for patients with neurological conditions. Dr. Ndirangu is also involved in clinical research and regularly contributes to medical journals, advancing the field of neurology in Kenya.",
            available=True,
            rating=4.7,
            reviews=103,
            phone="0711000001",
            years_practice=10,
            working_hours="Mon-Wed-Fri 8AM-3PM",
            fee=3500,
            duration=45,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[11].id,
            first_name="Mary",
            last_name="Atieno",
            email="mary.atieno@example.com",
            specialty="Orthopedics",
            specialties="Joint Replacement,Sports Medicine,Trauma Surgery,Minimally Invasive Procedures",
            profile_image="https://placehold.co/150x150/D97706/FFFFFF?text=MA",
            languages="English, Swahili, Italian",
            education="MBChB from University of Nairobi; Orthopedic Surgery Residency at Aga Khan University; Fellowship in Joint Replacement in Milan.",
            certifications="Fellow of the Royal College of Surgeons (FRCS); AO Trauma Certified; Minimally Invasive Surgery Certified.",
            working_days="Mon-Thu",
            consultation_type="Physical",
            verification_status="Verified",
            hospital_ids="1,2",
            bio="Dr. Atieno is a leading orthopedic surgeon with 15 years of experience in bone and joint care. She specializes in joint replacement surgeries, sports medicine, and trauma surgery. Her surgical precision and innovative techniques have helped hundreds of patients regain mobility and return to active lifestyles. Dr. Atieno is particularly passionate about minimally invasive procedures and has trained surgeons across East Africa. She believes in a holistic approach to orthopedic care, combining surgery with rehabilitation for optimal outcomes.",
            available=True,
            rating=4.9,
            reviews=156,
            phone="0711000002",
            years_practice=15,
            working_hours="Mon-Thu 7AM-3PM",
            fee=4000,
            duration=40,
            hospital_name=hospitals[0].name,
            hospital_location=hospitals[0].address,
            hospital_phone=hospitals[0].phone,
        ),
        Doctor(
            user_id=users[12].id,
            first_name="James",
            last_name="Kariuki",
            email="james.kariuki@example.com",
            specialty="General Practice",
            specialties="Preventive Medicine,Family Healthcare,Chronic Disease Management,Health Screenings",
            profile_image="https://placehold.co/150x150/4F46E5/FFFFFF?text=JK",
            languages="English, Swahili",
            education="MBChB from University of Nairobi; Master of Medicine in Family Medicine; Diploma in Public Health.",
            certifications="Kenya Medical Practitioners Board Certified; Advanced Cardiac Life Support (ACLS); Travel Medicine Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2",
            bio="Dr. Kariuki is a compassionate general practitioner with 5 years of experience in preventive medicine and family healthcare. He provides comprehensive medical care for patients of all ages, focusing on disease prevention, health promotion, and chronic disease management. His practice emphasizes building long-term doctor-patient relationships and he is known for his thorough approach to diagnostics. Dr. Kariuki is a strong advocate for community health and regularly conducts free medical camps in underserved areas.",
            available=True,
            rating=4.4,
            reviews=72,
            phone="0711000003",
            years_practice=5,
            working_hours="Mon-Fri 8AM-5PM",
            fee=1500,
            duration=15,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=users[13].id,
            first_name="Grace",
            last_name="Muthoni",
            email="grace.muthoni@example.com",
            specialty="Pediatrics",
            specialties="Child Development,Early Intervention,Growth Monitoring,Behavioral Health",
            profile_image="https://placehold.co/150x150/EC4899/FFFFFF?text=GM",
            languages="English, Swahili, Kikuyu",
            education="MBChB from University of Nairobi; Pediatric Residency at Kenyatta National Hospital; Masters in Child Development.",
            certifications="Kenya Pediatric Society Member; Developmental Behavioral Pediatrics Certified; Breastfeeding Counselor Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2,3",
            bio="Dr. Muthoni is a caring pediatrician with 7 years of focused experience in child development and wellness. She has a special interest in developmental pediatrics and early childhood intervention. Her warm and playful approach helps children feel comfortable during consultations, making healthcare visits a positive experience. Dr. Muthoni works closely with parents to monitor growth milestones, address behavioral concerns, and ensure optimal health outcomes for every child under her care.",
            available=True,
            rating=4.6,
            reviews=91,
            phone="0711000004",
            years_practice=7,
            working_hours="Mon-Fri 9AM-4PM",
            fee=2200,
            duration=25,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=users[14].id,
            first_name="Peter",
            last_name="Ochieng",
            email="peter.ochieng@example.com",
            specialty="Cardiology",
            specialties="Heart Failure Management,Interventional Cardiology,Cardiac Catheterization,Preventive Cardiology",
            profile_image="https://placehold.co/150x150/0891B2/FFFFFF?text=PO",
            languages="English, Swahili, Luo",
            education="MD from University of Nairobi; Cardiology Residency at Aga Khan University; Fellowship in Interventional Cardiology.",
            certifications="Fellow of the American College of Cardiology (FACC); Certified Interventional Cardiologist; Bariatric Endoscopy Certified.",
            working_days="Mon-Tue-Thu",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2",
            bio="Dr. Ochieng is an experienced cardiologist with 11 years of specialized practice in heart failure management and interventional cardiology. He has pioneered several cardiac catheterization procedures in the region and is recognized for his expertise in managing complex cardiovascular conditions. His patient-centric philosophy ensures that each individual receives a tailored treatment plan. Dr. Ochieng is actively involved in teaching and mentoring the next generation of cardiologists.",
            available=False,
            rating=4.8,
            reviews=118,
            phone="0711000005",
            years_practice=11,
            working_hours="Mon-Tue-Thu 8AM-4PM",
            fee=3200,
            duration=35,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=users[15].id,
            first_name="Susan",
            last_name="Wairimu",
            email="susan.wairimu@example.com",
            specialty="Dermatology",
            specialties="Skin Cancer Screening,Psoriasis Treatment,Vitiligo Care,Acne Management",
            profile_image="https://placehold.co/150x150/10B981/FFFFFF?text=SW",
            languages="English, Swahili, Kikuyu",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; Clinical Fellowship in Dermatopathology.",
            certifications="American Academy of Dermatology Fellow; Dermatopathology Board Certified; Mohs Surgery Trained.",
            working_days="Wed-Sat",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2,3",
            bio="Dr. Wairimu is a skilled dermatologist with 9 years of experience in skin cancer screening and medical dermatology. She is dedicated to early detection and treatment of skin cancers, utilizing dermoscopy and advanced biopsy techniques. Her expertise also includes treating chronic skin conditions like psoriasis, vitiligo, and severe acne. Dr. Wairimu conducts regular skin health workshops and believes in the importance of regular skin check-ups for early detection of abnormalities.",
            available=True,
            rating=4.7,
            reviews=85,
            phone="0711000006",
            years_practice=9,
            working_hours="Wed-Sat 10AM-5PM",
            fee=2800,
            duration=30,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=users[16].id,
            first_name="John",
            last_name="Kipkoech",
            email="john.kipkoech@example.com",
            specialty="General Practice",
            specialties="Family Medicine,Diabetes Management,Hypertension Care,Obesity Treatment",
            profile_image="https://placehold.co/150x150/6366F1/FFFFFF?text=JK",
            languages="English, Swahili, Kalenjin",
            education="MBChB from Moi University; Master of Medicine in Family Medicine; Executive MBA in Healthcare Management.",
            certifications="Kenya Medical Practitioners Board Certified; Diabetes Educator Certified; Hypertension Specialist Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="2,3",
            bio="Dr. Kipkoech is a dedicated GP with 6 years of strong focus on family medicine. He provides comprehensive primary care services including acute illness management, chronic disease monitoring, and preventive health screenings. His approachable demeanor and commitment to patient education help individuals take control of their health. Dr. Kipkoech is particularly skilled in managing lifestyle-related conditions such as diabetes, hypertension, and obesity through personalized care plans.",
            available=True,
            rating=4.5,
            reviews=78,
            phone="0711000007",
            years_practice=6,
            working_hours="Mon-Fri 8AM-4PM",
            fee=1800,
            duration=20,
            hospital_name=hospitals[1].name,
            hospital_location=hospitals[1].address,
            hospital_phone=hospitals[1].phone,
        ),
        Doctor(
            user_id=users[17].id,
            first_name="Lucy",
            last_name="Cherotich",
            email="lucy.cherotich@example.com",
            specialty="Orthopedics",
            specialties="Sports Injuries,Musculoskeletal Disorders,Ligament Tears,Rehabilitation",
            profile_image="https://placehold.co/150x150/F59E0B/FFFFFF?text=LC",
            languages="English, Swahili, Kalenjin",
            education="MBChB from University of Nairobi; Orthopedic Surgery Residency at Aga Khan University; Sports Medicine Fellowship in South Africa.",
            certifications="Fellow of the Royal College of Surgeons (FRCS); Sports Medicine Certified; Orthopedic Trauma Association Member.",
            working_days="Mon-Fri",
            consultation_type="Physical",
            verification_status="Verified",
            hospital_ids="3",
            bio="Dr. Cherotich is an accomplished orthopedic specialist with 12 years of experience in sports injuries and musculoskeletal disorders. She has worked with professional athletes and sports teams, providing expert care for ligament tears, fractures, and joint dislocations. Her clinic is equipped with state-of-the-art imaging and rehabilitation facilities. Dr. Cherotich believes in a multidisciplinary approach, collaborating with physiotherapists and sports scientists to ensure complete recovery and optimal performance for her patients.",
            available=True,
            rating=4.9,
            reviews=142,
            phone="0711000008",
            years_practice=12,
            working_hours="Mon-Fri 7AM-2PM",
            fee=3800,
            duration=40,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=users[18].id,
            first_name="Mark",
            last_name="Sang",
            email="mark.sang@example.com",
            specialty="Neurology",
            specialties="Stroke Care,Neurocritical Care,Epilepsy Management,Parkinson's Disease",
            profile_image="https://placehold.co/150x150/14B8A6/FFFFFF?text=MS",
            languages="English, Swahili",
            education="MD from University of Nairobi; Neurology Residency at Kenyatta National Hospital; Fellowship in Neurocritical Care.",
            certifications="Board Certified Neurologist; Neurocritical Care Society Member; Certified in Neurointensive Care.",
            working_days="Tue-Thu",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="3",
            bio="Dr. Sang is a skilled neurologist with 8 years of experience in stroke care and neurocritical care. He is part of a rapid response team that provides life-saving interventions for stroke patients. His expertise includes managing epilepsy, Parkinson's disease, and neuropathic pain. Dr. Sang is committed to providing compassionate care and clear communication to patients and their families during challenging neurological conditions. He actively participates in stroke awareness campaigns.",
            available=True,
            rating=4.6,
            reviews=97,
            phone="0711000009",
            years_practice=8,
            working_hours="Tue-Thu 9AM-4PM",
            fee=3400,
            duration=45,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=users[19].id,
            first_name="Nancy",
            last_name="Jeptoo",
            email="nancy.jeptoo@example.com",
            specialty="Pediatrics",
            specialties="Newborn Care,Neonatal Medicine,Premature Birth Care,Congenital Conditions",
            profile_image="https://placehold.co/150x150/F472B6/FFFFFF?text=NJ",
            languages="English, Swahili, Kalenjin",
            education="MBChB from Moi University; Pediatric Residency at Aga Khan University; Neonatal-Perinatal Medicine Fellowship.",
            certifications="Kenya Pediatric Society Fellow; Neonatal Resuscitation Program (NRP) Instructor; Breastfeeding Specialist Certified.",
            working_days="Mon-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="3",
            bio="Dr. Jeptoo is a board-certified pediatrician with 10 years of specialized experience in newborn care and neonatal medicine. She has extensive experience managing premature births, congenital conditions, and neonatal intensive care. Her gentle and nurturing approach provides comfort to both infants and their parents. Dr. Jeptoo is committed to ensuring every child receives the best possible start in life through comprehensive neonatal care and parental guidance.",
            available=True,
            rating=4.8,
            reviews=134,
            phone="0711000010",
            years_practice=10,
            working_hours="Mon-Fri 8AM-3PM",
            fee=2300,
            duration=25,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=users[20].id,
            first_name="Daniel",
            last_name="Kemboi",
            email="daniel.kemboi@example.com",
            specialty="Cardiology",
            specialties="Preventive Cardiology,Risk Assessment,Lifestyle Modification,Cardiac Wellness",
            profile_image="https://placehold.co/150x150/0E7490/FFFFFF?text=DK",
            languages="English, Swahili, Kalenjin",
            education="MD from Moi University; Cardiology Residency at Aga Khan University; Masters in Preventive Cardiology.",
            certifications="Preventive Cardiology Certified; Fellow of the American Heart Association; Cardiac Rehabilitation Specialist.",
            working_days="Mon-Wed-Fri",
            consultation_type="Both",
            verification_status="Verified",
            hospital_ids="3,1",
            bio="Dr. Kemboi is a prevention-focused cardiologist with 9 years of experience in promoting heart health and preventing cardiovascular diseases. He specializes in risk assessment, lifestyle modification programs, and non-invasive cardiac testing. His proactive approach helps patients identify and manage risk factors before they develop serious heart conditions. Dr. Kemboi conducts regular heart health seminars and has developed a community-based cardiac wellness program that has benefited thousands of patients.",
            available=True,
            rating=4.7,
            reviews=109,
            phone="0711000011",
            years_practice=9,
            working_hours="Mon-Wed-Fri 8AM-4PM",
            fee=2900,
            duration=35,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
        Doctor(
            user_id=users[21].id,
            first_name="Sarah",
            last_name="Jepchirchir",
            email="sarah.jepchirchir@example.com",
            specialty="Dermatology",
            specialties="Cosmetic Dermatology,Skin Rejuvenation,Anti-Aging Treatments,Reconstructive Procedures",
            profile_image="https://placehold.co/150x150/7C3AED/FFFFFF?text=SJ",
            languages="English, Swahili, Kalenjin",
            education="MBChB from University of Nairobi; Dermatology Residency at Kenyatta National Hospital; Cosmetic Surgery Fellowship.",
            certifications="American Academy of Dermatology Fellow; Cosmetic Dermatology Certified; Reconstructive Surgery Board Certified.",
            working_days="Tue-Sat",
            consultation_type="Online",
            verification_status="Verified",
            hospital_ids="3,1",
            bio="Dr. Jepchirchir is an expert dermatologist with 13 years of experience in cosmetic and medical skin care. She combines her artistic eye with medical expertise to deliver natural-looking aesthetic results. Her services range from anti-aging treatments and skin rejuvenation to complex reconstructive procedures. Dr. Jepchirir is known for her meticulous attention to detail and believes in enhancing each patient's natural beauty. She stays at the forefront of dermatological advances through continuous education.",
            available=False,
            rating=4.9,
            reviews=168,
            phone="0711000012",
            years_practice=13,
            working_hours="Tue-Sat 11AM-5PM",
            fee=3200,
            duration=30,
            hospital_name=hospitals[2].name,
            hospital_location=hospitals[2].address,
            hospital_phone=hospitals[2].phone,
        ),
    ]
    db.session.add_all(doctors)
    db.session.commit()
    print(f"Seeded {len(doctors)} doctors.")

    appointments = [
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime(2026, 7, 29, 10, 0, 0),
            appointment_time=time(10, 0),
            status="Scheduled",
            notes="Follow-up visit for hypertension check.",
        ),
        Appointment(
            patient_id=patients[1].id,
            doctor_id=doctors[1].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime(2026, 7, 30, 9, 0, 0),
            appointment_time=time(9, 0),
            status="Scheduled",
            notes="Child vaccination appointment.",
        ),
        Appointment(
            patient_id=patients[2].id,
            doctor_id=doctors[2].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 7, 31, 14, 0, 0),
            appointment_time=time(14, 0),
            status="Scheduled",
            notes="Skin rash consultation.",
        ),
        Appointment(
            patient_id=patients[3].id,
            doctor_id=doctors[3].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 1, 11, 0, 0),
            appointment_time=time(11, 0),
            status="Completed",
            notes="Routine cardiac screening.",
        ),
        Appointment(
            patient_id=patients[4].id,
            doctor_id=doctors[4].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 8, 2, 8, 30, 0),
            appointment_time=time(8, 30),
            status="Cancelled",
            notes="Annual orthopedic check-up.",
        ),
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[5].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 8, 3, 9, 0, 0),
            appointment_time=time(9, 0),
            status="Scheduled",
            notes="General health checkup.",
        ),
        Appointment(
            patient_id=patients[1].id,
            doctor_id=doctors[6].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 8, 4, 10, 30, 0),
            appointment_time=time(10, 30),
            status="Completed",
            notes="Child development assessment.",
        ),
        Appointment(
            patient_id=patients[2].id,
            doctor_id=doctors[7].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 5, 15, 0, 0),
            appointment_time=time(15, 0),
            status="Scheduled",
            notes="Heart failure follow-up.",
        ),
        Appointment(
            patient_id=patients[3].id,
            doctor_id=doctors[8].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime(2026, 8, 6, 13, 0, 0),
            appointment_time=time(13, 0),
            status="Completed",
            notes="Skin cancer screening.",
        ),
        Appointment(
            patient_id=patients[4].id,
            doctor_id=doctors[9].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 7, 8, 0, 0),
            appointment_time=time(8, 0),
            status="Scheduled",
            notes="Sports injury consultation.",
        ),
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[10].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime(2026, 8, 8, 11, 30, 0),
            appointment_time=time(11, 30),
            status="Cancelled",
            notes="Neurology follow-up.",
        ),
        Appointment(
            patient_id=patients[1].id,
            doctor_id=doctors[11].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 9, 9, 30, 0),
            appointment_time=time(9, 30),
            status="Completed",
            notes="Newborn checkup.",
        ),
        Appointment(
            patient_id=patients[2].id,
            doctor_id=doctors[12].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime(2026, 8, 10, 14, 30, 0),
            appointment_time=time(14, 30),
            status="Scheduled",
            notes="Preventive cardiology consultation.",
        ),
        Appointment(
            patient_id=patients[3].id,
            doctor_id=doctors[13].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 11, 10, 0, 0),
            appointment_time=time(10, 0),
            status="Completed",
            notes="Dermatology cosmetic treatment.",
        ),
        Appointment(
            patient_id=patients[4].id,
            doctor_id=doctors[14].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 8, 12, 16, 0, 0),
            appointment_time=time(16, 0),
            status="Scheduled",
            notes="Chronic disease review.",
        ),
        Appointment(
            patient_id=patients[0].id,
            doctor_id=doctors[0].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 13, 8, 30, 0),
            appointment_time=time(8, 30),
            status="Completed",
            notes="Post-surgery follow-up.",
        ),
        Appointment(
            patient_id=patients[1].id,
            doctor_id=doctors[1].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 8, 14, 9, 0, 0),
            appointment_time=time(9, 0),
            status="Scheduled",
            notes="Vaccination appointment.",
        ),
        Appointment(
            patient_id=patients[2].id,
            doctor_id=doctors[2].id,
            hospital_id=hospitals[0].id,
            appointment_date=datetime(2026, 8, 15, 11, 0, 0),
            appointment_time=time(11, 0),
            status="Cancelled",
            notes="Acne treatment follow-up.",
        ),
        Appointment(
            patient_id=patients[3].id,
            doctor_id=doctors[3].id,
            hospital_id=hospitals[1].id,
            appointment_date=datetime(2026, 8, 16, 15, 30, 0),
            appointment_time=time(15, 30),
            status="Completed",
            notes="Neurological exam.",
        ),
        Appointment(
            patient_id=patients[4].id,
            doctor_id=doctors[4].id,
            hospital_id=hospitals[2].id,
            appointment_date=datetime(2026, 8, 17, 13, 0, 0),
            appointment_time=time(13, 0),
            status="Scheduled",
            notes="Joint replacement consultation.",
        ),
    ]

    patient_review_pool = [
        "Alice Johnson", "Brian Mwangi", "Carol Ndegwa", "David Otieno", "Eva Kipchoge",
        "Samuel Kipruto", "Mercy Wanjiru", "Patrick Muriithi", "Agnes Chepkemoi", "Elijah Omondi",
        "Beatrice Njeri", "Victor Kibet", "Lydia Achieng", "Geoffrey Kipchumba", "Priscilla Jelimo"
    ]

    review_comments_pool = [
        "Excellent care and very professional. Highly recommended!",
        "Very knowledgeable and took time to explain everything.",
        "Great experience overall. The staff was friendly and helpful.",
        "Dr. was thorough and attentive. Would definitely come back.",
        "Good service but slightly long wait time.",
        "Outstanding bedside manner and clear explanations.",
        "Felt very comfortable and well taken care of.",
        "Exceeded my expectations. Truly a great doctor.",
        "Very patient with all my questions and concerns.",
        "A wonderful experience from start to finish.",
        "Highly skilled and compassionate. Thank you!",
        "The best doctor I have ever consulted. Very professional.",
        "Prompt service and very detailed diagnosis.",
        "A truly caring doctor who puts patients first.",
        "Amazing care and follow-up. Very satisfied.",
    ]

    time_slots = [
        time(8, 0), time(8, 30), time(9, 0), time(9, 30), time(10, 0),
        time(10, 30), time(11, 0), time(14, 0), time(14, 30), time(15, 0),
        time(15, 30), time(16, 0),
    ]

    db.session.add_all(appointments)
    db.session.commit()
    print(f"Seeded {len(appointments)} appointments.")

    reviews = []
    for i, doctor in enumerate(doctors):
        used_appts = [a for a in appointments if a.doctor_id == doctor.id]
        for j in range(min(5, len(used_appts))):
            appt = used_appts[j]
            patient_name = patient_review_pool[(i * 5 + j) % len(patient_review_pool)]
            comment = review_comments_pool[(i * 5 + j) % len(review_comments_pool)]
            rating = (4 + (j % 2)) if j < 4 else 5
            reviews.append(
                Review(
                    appointment_id=appt.id,
                    patient_id=appt.patient_id,
                    doctor_id=doctor.id,
                    rating=rating,
                    comment=comment,
                )
            )

    db.session.add_all(reviews)
    db.session.commit()
    print(f"Seeded {len(reviews)} reviews.")

    print("Done seeding!")
