"""add relationships and new fields

Revision ID: 16c669a444a5
Revises: a6f9eb92d594
Create Date: 2026-07-28 23:15:38.841177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c669a444a5'
down_revision = 'a6f9eb92d594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_appointment')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_appointment_email_address'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_appointment_phone'), type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_appointment_patient_id_patient'), 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointment_doctor_id_doctor'), 'doctor', ['doctor_id'], ['id'])
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('email_address')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_doctor_hospital_id_hospital'), 'hospital', ['hospital_id'], ['id'])

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_review_email_address'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_review_phone'), type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_review_doctor_id_doctor'), 'doctor', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_review_patient_id_patient'), 'patient', ['patient_id'], ['id'])
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')
        batch_op.drop_column('email_address')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email_address', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_review_patient_id_patient'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_review_doctor_id_doctor'), type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_review_phone'), ['phone'])
        batch_op.create_unique_constraint(batch_op.f('uq_review_email_address'), ['email_address'])
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('comment')
        batch_op.drop_column('rating')

    with op.batch_alter_table('hospital', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doctor_hospital_id_hospital'), type_='foreignkey')
        batch_op.drop_column('hospital_id')
        batch_op.drop_column('specialty')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('email_address', sa.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_appointment_doctor_id_doctor'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointment_patient_id_patient'), type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_appointment_phone'), ['phone'])
        batch_op.create_unique_constraint(batch_op.f('uq_appointment_email_address'), ['email_address'])
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('status')
        batch_op.drop_column('appointment_date')

    op.create_table('_alembic_tmp_appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('appointment_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_appointment_doctor_id_doctor')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_appointment_patient_id_patient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment'))
    )
    # ### end Alembic commands ###
