"""initial schema

Revision ID: 88132c2bbacb
Revises: 
Create Date: 2026-07-29 10:17:55.052683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88132c2bbacb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email_address LIKE '%@%'", name=op.f('ck_hospital_ck_hospital_email_format')),
    sa.CheckConstraint('length(first_name) >= 1', name=op.f('ck_hospital_ck_hospital_first_name_length')),
    sa.CheckConstraint('length(last_name) >= 1', name=op.f('ck_hospital_ck_hospital_last_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospital')),
    sa.UniqueConstraint('email_address', name=op.f('uq_hospital_email_address')),
    sa.UniqueConstraint('phone', name=op.f('uq_hospital_phone'))
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email_address LIKE '%@%'", name=op.f('ck_patient_ck_patient_email_format')),
    sa.CheckConstraint('length(first_name) >= 1', name=op.f('ck_patient_ck_patient_first_name_length')),
    sa.CheckConstraint('length(last_name) >= 1', name=op.f('ck_patient_ck_patient_last_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient')),
    sa.UniqueConstraint('email_address', name=op.f('uq_patient_email_address')),
    sa.UniqueConstraint('phone', name=op.f('uq_patient_phone'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email_address LIKE '%@%'", name=op.f('ck_users_ck_user_email_format')),
    sa.CheckConstraint('length(first_name) >= 1', name=op.f('ck_users_ck_user_first_name_length')),
    sa.CheckConstraint('length(last_name) >= 1', name=op.f('ck_users_ck_user_last_name_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email_address', name=op.f('uq_users_email_address')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email_address LIKE '%@%'", name=op.f('ck_doctor_ck_doctor_email_format')),
    sa.CheckConstraint('length(first_name) >= 1', name=op.f('ck_doctor_ck_doctor_first_name_length')),
    sa.CheckConstraint('length(last_name) >= 1', name=op.f('ck_doctor_ck_doctor_last_name_length')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], name=op.f('fk_doctor_hospital_id_hospital')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor')),
    sa.UniqueConstraint('email_address', name=op.f('uq_doctor_email_address')),
    sa.UniqueConstraint('phone', name=op.f('uq_doctor_phone'))
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled')", name=op.f('ck_appointment_ck_appointment_status')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_appointment_doctor_id_doctor')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_appointment_patient_id_patient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment'))
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_review_ck_review_rating_range')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name=op.f('fk_review_doctor_id_doctor')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_review_patient_id_patient')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('appointment')
    op.drop_table('doctor')
    op.drop_table('users')
    op.drop_table('patient')
    op.drop_table('hospital')
    # ### end Alembic commands ###
