"""Add doctor dashboard models

Revision ID: 6e810c0fff24
Revises: 7c89dcd24d14
Create Date: 2026-08-03 05:12:33.324182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e810c0fff24'
down_revision = '7c89dcd24d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("doc_type IN ('medical_license', 'certificate', 'cv', 'insurance', 'verification', 'other')", name=op.f('ck_doctor_documents_ck_document_type')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_doctor_documents_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_documents'))
    )
    op.create_table('doctor_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('is_vacation', sa.Boolean(), nullable=False),
    sa.Column('is_emergency_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_doctor_schedules_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_schedules'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_appointment_id', sa.Integer(), nullable=True),
    sa.Column('related_patient_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('appointment_booked', 'appointment_cancelled', 'documents_uploaded', 'followup_reminder', 'admin_announcement')", name=op.f('ck_notifications_ck_notification_type')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_notifications_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['related_appointment_id'], ['appointments.id'], name=op.f('fk_notifications_related_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['related_patient_id'], ['patients.id'], name=op.f('fk_notifications_related_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicine', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_prescriptions_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name=op.f('fk_prescriptions_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], name=op.f('fk_prescriptions_medical_record_id_medical_records')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_prescriptions_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescriptions'))
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepting_patients', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('appointment_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consultation_fee', sa.Integer(), nullable=True))

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('lab_requests', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_medical_records_doctor_id_doctors'), 'doctors', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_medical_records_patient_id_patients'), 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_medical_records_patient_id_patients'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_medical_records_doctor_id_doctors'), type_='foreignkey')
        batch_op.drop_column('lab_requests')
        batch_op.drop_column('treatment_plan')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('patient_id')
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('consultation_fee')
        batch_op.drop_column('appointment_duration')
        batch_op.drop_column('accepting_patients')

    op.drop_table('prescriptions')
    op.drop_table('notifications')
    op.drop_table('doctor_schedules')
    op.drop_table('doctor_documents')
    # ### end Alembic commands ###
