"""increase_profile_image_size_to_text

Revision ID: 715a630d79ca
Revises: 96093ff68d57
Create Date: 2026-07-31 03:30:05.324336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715a630d79ca'
down_revision = '96093ff68d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
