"""Add hospital_id to Doctor, create Staff model

Revision ID: 7c89dcd24d14
Revises: e4746ebdbdb4
Create Date: 2026-08-03 01:22:05.681955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c89dcd24d14'
down_revision = 'e4746ebdbdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('profile_image', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('length(first_name) >= 1', name=op.f('ck_staff_ck_staff_first_name_length')),
    sa.CheckConstraint('length(last_name) >= 1', name=op.f('ck_staff_ck_staff_last_name_length')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_staff_hospital_id_hospitals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff')),
    sa.UniqueConstraint('email', name=op.f('uq_staff_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_staff_phone'))
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_doctors_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doctors_hospital_id_hospitals'), type_='foreignkey')
        batch_op.drop_column('hospital_id')

    op.drop_table('staff')
    # ### end Alembic commands ###
