"""add_medical_records_table

Revision ID: 87895e445c3e
Revises: g2h3i4j5k6l7
Create Date: 2026-07-31 02:17:42.479310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87895e445c3e'
down_revision = 'g2h3i4j5k6l7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_medical_records_appointment_id_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records')),
    sa.UniqueConstraint('appointment_id', name=op.f('uq_medical_records_appointment_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    # ### end Alembic commands ###
