"""add_profile_image_to_users

Revision ID: 96093ff68d57
Revises: 93537d388d9f
Create Date: 2026-07-31 03:08:46.313222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96093ff68d57'
down_revision = '93537d388d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
