"""Add hospital_id to doctors

Revision ID: d5c27a503edc
Revises: 761d0c231aa6
Create Date: 2026-07-30 15:17:08.255491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c27a503edc'
down_revision = '761d0c231aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_doctors_hospital_id_hospitals'), 'hospitals', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_doctors_hospital_id_hospitals'), type_='foreignkey')
        batch_op.drop_column('hospital_id')
    # ### end Alembic commands ###
