"""Initial migration

Revision ID: e4746ebdbdb4
Revises: 715a630d79ca
Create Date: 2026-08-03 00:39:46.345897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4746ebdbdb4'
down_revision = '715a630d79ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_token'), ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_token'), type_='unique')
        batch_op.drop_column('token')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
